// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thunaolandjuvuhvbsds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRodW5hb2xhbmRqdXZ1aHZic2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTEyMjQsImV4cCI6MjA3MzYyNzIyNH0.Qxv1DYPL4M15R4VVOm7Bph4ZKCjiClnNRvuMyPXZQts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});